name: Docker Publish

on:
  pull_request:
    types: [synchronize]

#on:
#  push:
#    branches: [ main ]
#    tags:
#      - '*'

jobs:
  docker_publish:
    # run workflow only on numaproj/numaflow-rs repository
#    if: ${{ github.repository }} == "numaproj/numaflow-rs"
    name: Build, Tag, and Push Image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dockerfile_paths: [
          "examples/map-cat"
        ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Quay.io registry
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.NUMAIO_USERNAME }}
          password: ${{ secrets.NUMAIO_PASSWORD }}
      - name: Build, tag, and push images
        run: ./hack/update_examples.sh --build-push-example ${{ matrix.dockerfile_paths }}

